# Managed by tfroot-github (gh-dependabot.tf); local edits are overwritten.
"updates":
- "directory": "/"
  "groups":
    "github-actions":
      "patterns":
      - "*"
  "package-ecosystem": "github-actions"
  "schedule":
    "interval": "daily"
- "directory": "/"
  "groups":
    "opentofu":
      "patterns":
      - "*"
  "package-ecosystem": "opentofu"
  "schedule":
    "interval": "daily"
"version": 2
